version: "3.7"

services: 
    
    mariadb: 
        image: mariadb:10.4.18
        restart: always
        ports: 
            - 3306:3306
        volumes: 
            - ./mariadb/conf.d:/etc/mysql/conf.d
        env_file: .env                
        environment: 
            TZ: Asia/Seoul
    
    redis:
        image: redis:latest
        restart: always
        hostname: redis6379
        ports: 
            - 6379:6379
        command: redis-server
